Repository openedx/devstack, pull requests merged in 2018-10, with the labels that each got.

#335 Add instructions on how to fix broken docker volume setup in Pycharm
  docs/pycharm_integration.rst
Labels: community manager review, open-source-contribution

#342 Edit devstack startup instructions
  README.rst
Labels: awaiting prioritization, open-source-contribution

#343 Updated readme to include links to more current docs
  README.rst
Labels: open-source-contribution, waiting on author

#344 Improve: fix typo in makefile
  Makefile
Labels: awaiting prioritization, open-source-contribution

#345 Make sure OPENEDX_GIT_BRANCH is honoured during clone
  repo.sh
Labels: awaiting prioritization, open-source-contribution
