Repository openedx/devstack, pull requests merged in 2020-05, with the labels that each got.

#515 Increase Docker Compose HTTP timeout
  options.mk
Labels: awaiting prioritization, open-source-contribution

#508 Update MySQL databases initialization SQL scripts
  README.rst
  dump-db.sh
  ecommerce.sql
  edxapp.sql
  edxapp_csmh.sql
  update-dbs-init-sql-scripts.sh
Labels: engineering review, open-source-contribution

#533 Add back loading of local.mk
  Makefile
Labels: needs triage, open-source-contribution

#535 [BD-6] Add tests in python 3.8
  .travis.yml
Labels: needs triage, open-source-contribution

#532 Multiple devstack releases with one machine
  Makefile
  Makefile.edx
  README.rst
  course-generator/create-courses.sh
  destroy.sh
  docker-compose-analytics-pipeline.yml
  docker-compose-marketing-site.yml
  docker-compose-watchers-nfs.yml
  docker-compose-watchers.yml
  docker-compose-xqueue.yml
  docker-compose.yml
  docs/devpi.rst
  gather-feature-toggle-state.sh
  in
  load-db.sh
  marketing.mk
  options.mk
  provision-analyticspipeline.sh
  provision-credentials.sh
  provision-e2e.sh
  provision-ecommerce.sh
  provision-forum.sh
  provision-ida-user.sh
  provision-ida.sh
  provision-lms.sh
  provision-marketing.sh
  provision-notes.sh
  provision-registrar.sh
  provision-retirement-user.sh
  provision-xqueue.sh
  provision.sh
  update-dbs-init-sql-scripts.sh
  upgrade_mongo_3_6.sh
Labels: engineering review, open-source-contribution
