Repository openedx/devstack, pull requests merged in 2020-08, with the labels that each got.

#556 [BD-14] Add Content Libraries v2 authoring MFE
  README.rst
  docker-compose-host-nfs.yml
  docker-compose-host.yml
  docker-compose-sync.yml
  docker-compose.yml
  docker-sync.yml
  options.mk
  repo.sh
Labels: blended, blocked by other work

#594 Do not use openedx release for registrar and edx-mktg docker images.
  docker-compose-marketing-site.yml
  docker-compose.yml
Labels: awaiting prioritization, open-source-contribution

#569 Updated `README` to include necessary information when running multiple isolated devstacks for same host.
  README.rst
Labels: cc-reviewer, needs triage, open-source-contribution

#599 Remove `xqueue` from `DEFAULT_SERVICES` fix for PR #564.
  options.mk
Labels: needs triage, open-source-contribution
