Repository openedx/devstack, pull requests merged in 2023-08, with the labels that each got.

#1133 replaced dev.down with dev.remove-containers
  docs/devstack_interface.rst
  docs/getting_started.rst
  docs/workflow.rst
Labels: open-source-contribution, waiting on author

#1122 docs: Update Docker links in Getting Started docs
  docs/getting_started.rst
Labels: open-source-contribution, waiting for eng review

#1153 fix: add names to redis and mongo volumes
  docker-compose.yml
Labels: open-source-contribution, waiting for eng review

#1149 docs: update superuser username in the getting_started.rst file
  docs/getting_started.rst
Labels: waiting for eng review
